# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_constriant.xdc

# Block Designs: bd/lab_5_top/lab_5_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top || ORIG_REF_NAME==lab_5_top} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_clock_div_25MHz_0_0/lab_5_top_clock_div_25MHz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_clock_div_25MHz_0_0 || ORIG_REF_NAME==lab_5_top_clock_div_25MHz_0_0} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_clock_div_115200_0_0/lab_5_top_clock_div_115200_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_clock_div_115200_0_0 || ORIG_REF_NAME==lab_5_top_clock_div_115200_0_0} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_controls_0_0/lab_5_top_controls_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_controls_0_0 || ORIG_REF_NAME==lab_5_top_controls_0_0} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_debounce_0_0/lab_5_top_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_debounce_0_0 || ORIG_REF_NAME==lab_5_top_debounce_0_0} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_framebuffer_0_0/lab_5_top_framebuffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_framebuffer_0_0 || ORIG_REF_NAME==lab_5_top_framebuffer_0_0} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_my_alu_0_0/lab_5_top_my_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_my_alu_0_0 || ORIG_REF_NAME==lab_5_top_my_alu_0_0} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_pixel_pusher_0_0/lab_5_top_pixel_pusher_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_pixel_pusher_0_0 || ORIG_REF_NAME==lab_5_top_pixel_pusher_0_0} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_regs_0_0/lab_5_top_regs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_regs_0_0 || ORIG_REF_NAME==lab_5_top_regs_0_0} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_uart_0_0/lab_5_top_uart_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_uart_0_0 || ORIG_REF_NAME==lab_5_top_uart_0_0} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_vga_ctrl_0_0/lab_5_top_vga_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_vga_ctrl_0_0 || ORIG_REF_NAME==lab_5_top_vga_ctrl_0_0} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_blk_mem_gen_0_1/lab_5_top_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_blk_mem_gen_0_1 || ORIG_REF_NAME==lab_5_top_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/lab_5_top/ip/lab_5_top_blk_mem_gen_0_2/lab_5_top_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_5_top_blk_mem_gen_0_2 || ORIG_REF_NAME==lab_5_top_blk_mem_gen_0_2} -quiet] -quiet

# XDC: bd/lab_5_top/lab_5_top_ooc.xdc
